### ISSUE TITLE
React Native竞赛邀请

### ISSUE THREAD

**Issue by poberwong** [iwgang/GankCamp-React-Native#4]
[我司](https://applean.cn) 最近举办了一期竞赛活动，有兴趣的可以来尝试参加参加！

**Comment by iwgang** [comment]
好棒的活动，可惜最近公司忙成狗了...

**Comment by poberwong** [comment]
好吧，你可以加一下群，以后可以技术上多多交流 ；我的账号 634611300，微信QQ都是这个。
