### ISSUE TITLE
npm i -S realm 报错

### ISSUE THREAD

**Issue by jeasinlee** [iwgang/GankCamp-React-Native#8]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-S" "realm"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! path D:\react_redux\Gank2016\node_modules\.staging\fstream-fdd71f1b
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'D:\react_redux\Gank2016\node_modules\.staging\fstream-fdd71f1b' -> 'D:\react_redux\Gank2016\node_modules
\fstream'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:117:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'D:\react_redux\Gank2016\node_modules\.staging\fstream-fdd71f1b' -> 'D:\react_redux\Gank2016\node_modules
\fstream'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'D:\react_redux\Gank2016\node_modules\.staging\fstream-fdd71f1b' -> 'D:\react_redux\Gank2016\node_modu
les\fstream'
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:117:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'D:\react_redux\Gank2016\node_modules\.staging\fstream-fdd71f1b' -> 'D:\react_redux\Gank2016\node_modules
\fstream'
npm ERR!     at Error (native) parent: 'Gank2016' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\react_redux\Gank2016\npm-debug.log

D:\react_redux\Gank2016>cnpm i -S realm
node-pre-gyp http GET https://static.realm.io/node-pre-gyp/realm-v0.15.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://static.realm.io/node-pre-gyp/realm-v0.15.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for realm@0.15.0 and node@6.2.2 (node-v48 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http connect ETIMEDOUT 104.16.77.48:443

D:\react_redux\Gank2016\node_modules\.0.15.0@realm>node "C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gy
p.js" clean

D:\react_redux\Gank2016\node_modules\.0.15.0@realm>node "C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gy
p.js" configure --fallback-to-build --module=D:\react_redux\Gank2016\node_modules\.0.15.0@realm\compiled\node-v48_win32_x64\realm.node --module_name=realm --mod
ule_path=D:\react_redux\Gank2016\node_modules\.0.15.0@realm\compiled\node-v48_win32_x64
Traceback (most recent call last):
  File "C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1988, in GenerateOutput
    generator_flags))
  File "C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 927, in _GenerateProject
    return _GenerateMSVSProject(project, options, version, generator_flags)
  File "C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1028, in _GenerateMSVSProject
    _AddAccumulatedActionsToMSVS(p, spec, actions_to_add)
  File "C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 468, in _AddAccumulatedActionsToM
SVS
    cmd=command)
  File "C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 438, in _AddCustomBuildToolForMSV
S
    _ConfigFullName(config_name, c_data), tools=[tool])
  File "C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\gyp\pylib\gyp\MSVSProject.py", line 181, in AddFileConfig
    raise ValueError('AddFileConfig: file "%s" not in project.' % path)
ValueError: AddFileConfig: file "..\..\binding.gyp" not in project.
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jixiang_Li\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin
\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\react_redux\\Gank2016\\node_modules\\.0.15.0@realm\\compiled\\node-v48_win32_x64\\realm.node" "--
module_name=realm" "--module_path=D:\\react_redux\\Gank2016\\node_modules\\.0.15.0@realm\\compiled\\node-v48_win32_x64"
gyp ERR! cwd D:\react_redux\Gank2016\node_modules\.0.15.0@realm
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\react_redux\Gank2016\node_modules\.0.15.0@realm\compile
d\node-v48_win32_x64\realm.node --module_name=realm --module_path=D:\react_redux\Gank2016\node_modules\.0.15.0@realm\compiled\node-v48_win32_x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\react_redux\Gank2016\node_modules\.0.6.32@node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\react_redux\\Gank2016\\node_modules\\.0.6.32@node-pre-gyp\\bin\\node-pre-gyp" "install" "--
fallback-to-build"
node-pre-gyp ERR! cwd D:\react_redux\Gank2016\node_modules\.0.15.0@realm
node-pre-gyp ERR! node -v v6.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\react_redux\Gank2016\node_modules\.0.15.0@realm\compiled\node-v48_win32_x64\realm.node
 --module_name=realm --module_path=D:\react_redux\Gank2016\node_modules\.0.15.0@realm\compiled\node-v48_win32_x64' (1)
Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npminstall version: 2.12.0
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\Jixiang_Li\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --use
rconfig=C:\Users\Jixiang_Li\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org -S realm

**Comment by iwgang** [comment]
去 realm 官方看下具体安装说明

**Comment by jeasinlee** [comment]
@iwgang 谢谢，我已经安装可以了，应该是realm版本问题。指定用0.14.3。
